version: "3.9"

services:
  web-server:
    build:
      context: ./
      dockerfile: ./packaging/Dockerfile.web-server
    pull_policy: always
    restart: always
    expose:
      - "8080"
    environment:
      - SYSTEM_CONFIGURATION_DEFAULT_THEME=light
      - BASEURL=${ASSETS_URL}
      - ASSETS_BUCKET=${ASSETS_BUCKET}
      - ASSETS_URL=${ASSETS_URL}
      - OSS_ENABLED=${OSS_ENABLED}
      - OSS_CLIENT_TYPE=${OSS_CLIENT_TYPE}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
    env_file:
      - ".env"
    networks:
      - apitable

  imageproxy-server:
    image: docker.io/apitable/imageproxy-server:latest
    pull_policy: always
    restart: always
    expose:
      - "8080"
    environment:
      - TZ={TIMEZONE}
      - BASEURL=${ASSETS_URL}
      - ASSETS_BUCKET=${ASSETS_BUCKET}
      - ASSETS_URL=${ASSETS_URL}
      - OSS_ENABLED=${OSS_ENABLED}
      - OSS_CLIENT_TYPE=${OSS_CLIENT_TYPE}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
    networks:
      - apitable

  backend-server:
    build:
      context: ./
      dockerfile: ./packaging/Dockerfile.backend-server
    pull_policy: always
    restart: always
    env_file:
      - ".env"
    expose:
      - "8081"
    environment:
      - ENV NODE_OPTIONS="--max-old-space-size=16384 --max-http-header-size=32768"
      - INSTANCE_MAX_MEMORY=8192M
      - UV_THREADPOOL_SIZE=16
      - TZ=${TIMEZONE}
      - DEFAULT_TIME_ZONE=${TIMEZONE}
      - MAX_HTTP_HEADER_SIZE=64KB
      - MAX_FILE_SIZE=1GB
      - MAX_REQUEST_SIZE=1GB
      - REDIS_DB=1
      - MAIL_SSL_ENABLE=false
      - SKIP_GLOBAL_WIDGET_AUDIT=true
      - ASSETS_BUCKET=${ASSETS_BUCKET}
      - ASSETS_URL=${ASSETS_URL}
      - OSS_ENABLED=${OSS_ENABLED}
      - OSS_CLIENT_TYPE=${OSS_CLIENT_TYPE}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_REGION=${AWS_REGION}

    networks:
      - apitable
    depends_on:
      init-db:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -sS 'http://localhost:8081' || exit 1"]
      interval: 5s
      timeout: 5s
      start_period: 30s
      retries: 60

  room-server:
    build:
      context: ./
      dockerfile: ./packaging/Dockerfile.room-server
    pull_policy: always
    restart: always
    expose:
      - "3333"
      - "3334"
      - "3001"
      - "3002"
      - "3006"
      - "3005"
      - "3007"
    env_file:
      - ".env"
    environment:
      - TZ=${TIMEZONE}
      - NODE_ENV=${ENV}
      - NODE_OPTIONS=--max-old-space-size=24576 --max-http-header-size=32768
      - INSTANCE_MAX_MEMORY=12288M
      - UV_THREADPOOL_SIZE=24
      - ENABLE_SOCKET=true
      - REDIS_DB=3
      - SERVER_MAX_FIELD_COUNT=500
      - SERVER_MAX_RECORD_COUNT=200000
      - API_MAX_MODIFY_RECORD_COUNTS=50
      - LIMIT_POINTS=50
      - MYSQL_CONNECTION_LIMIT=20
      - BASEURL=${ASSETS_URL}
      - ASSETS_BUCKET=${ASSETS_BUCKET}
      - ASSETS_URL=${ASSETS_URL}
      - OSS_ENABLED=${OSS_ENABLED}
      - OSS_CLIENT_TYPE=${OSS_CLIENT_TYPE}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
    networks:
      - apitable

  databus-server:
    image: docker.io/apitable/databus-server:latest
    pull_policy: always
    restart: always
    expose:
      - "8625"
    env_file:
      - ".env"
    environment:
      - TZ=${TIMEZONE}
      - BASEURL=${ASSETS_URL}
      - ASSETS_BUCKET=${ASSETS_BUCKET}
      - ASSETS_URL=${ASSETS_URL}
      - OSS_ENABLED=${OSS_ENABLED}
      - OSS_CLIENT_TYPE=${OSS_CLIENT_TYPE}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
    networks:
      - apitable

  gateway:
    build:
      context: ./gateway
      dockerfile: ../packaging/Dockerfile.openresty
    pull_policy: always
    restart: always
    ports:
      - 8088:80
      - 8443:8443
    environment:
      - TZ=${TIMEZONE}
      - BASEURL=${ASSETS_URL}
      - ASSETS_BUCKET=${ASSETS_BUCKET}
      - ASSETS_URL=${ASSETS_URL}
      - OSS_ENABLED=${OSS_ENABLED}
      - OSS_CLIENT_TYPE=${OSS_CLIENT_TYPE}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
    networks:
      - apitable
    depends_on:
      web-server:
        condition: service_started
      imageproxy-server:
        condition: service_started
      backend-server:
        condition: service_healthy
      room-server:
        condition: service_started
      init-appdata:
        condition: service_completed_successfully
      
  init-db:
    build:
      context: ./init-db
      dockerfile: Dockerfile
    pull_policy: always
    environment:
      - TZ=${TIMEZONE}
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USERNAME}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_TABLE_PREFIX=${DATABASE_TABLE_PREFIX}
      - ACTION=update
    networks:
      - apitable

  init-appdata:
    image: docker.io/apitable/init-appdata:v1.8.0-alpha_build232
    pull_policy: always
    env_file:
      - ".env"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
      - ASSETS_BUCKET=${ASSETS_BUCKET}
      - SKIP_TEMPLATE_CENTER_LOADER=true
      - SKIP_TEMPLATE_CENTER_CONFIG_LOADER=true
      - SKIP_WIDGET_CENTER_LOADER=false
      - SKIP_AUTOMATION_LOADER=false
      - SKIP_LAB_FEATURE_LOADER=false
      - SKIP_WIZARD_LOADER=false
    networks:
      - apitable
    depends_on:
      init-db:
        condition: service_completed_successfully

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.9-management
    pull_policy: always
    restart: always
    volumes:
      - ./.data/rabbitmq:/var/lib/rabbitmq
    expose:
      - "5671"
      - "5672"
      - "15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - apitable

networks:
  apitable:
    name: apitable_default
    driver: bridge
