services:
  - type: web
    name: apitable
    env: docker
    plan: pro-plus
    envVars:
      - key: PORT
        value: 80
    volumes:
      - name: apitable-data
        path: /apitable
    dockerfile: |
      FROM apitable/all-in-one:latest
      EXPOSE 80
